### ISSUE TITLE
Implement a new Figma design

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/caspion#143]
Currently there is a left panel and right panel for the importers/exporters and the configuration width is very limited. This makes the flow of editing configuration not user friendly.

The configuration of each importer/exporter should open in a popup modal that is large enough to edit the configuration comfortably.

Perhaps we should use this to replace the left/right panel ui with the ui currently used for the progress indication. 

So each account will have a card that will have a settings icon. Clicking that settings icon will open a popup modal.

When running the scraping, the settings icon will be replaced with the progress indication.

A rough and ugly sketch:

![Screen Shot 2020-12-17 at 13 58 19](https://user-images.githubusercontent.com/7272927/102485907-e8bac080-4070-11eb-84f9-9f2150486e46.png)

**Comment by baruchiro** [comment]
Do you expect this to be combined with the statuses block in #135, right?

I think it is a good and easy improvement, and that is why we can consider to implement it even before we are consulting with a UX expert.

**Comment by baruchiro** [comment]
There is a request from old users the validate the importer when it added. https://github.com/baruchiro/israeli-bank-scrapers-desktop/issues/56

I'm putting it here to think if we want to handle it with this issue, or to open an issue after this finished.

**Comment by Moshet** [comment]
> There is a request from old users the validate the importer when it added. [baruchiro/israeli-bank-scrapers-desktop#56](https://github.com/baruchiro/israeli-bank-scrapers-desktop/issues/56)
> 
> I'm putting it here to think if we want to handle it with this issue, or to open an issue after this finished.

I can assist with planning a user friendly UX

**Comment by baruchiro** [comment]
@Moshet AMAZING!

You're welcome to download and install the application and give us feedback.

To download, for now until we will have a release (soon!), select the latest action from this link:
https://github.com/brafdlog/budget-tracking/actions?query=workflow%3ABuild%2FRelease+branch%3AunifyRepos
And after entering the item, you will find `artifacts` on the bottom, download the right one depends on your system.

If you need out assistant, open a discussion [here](https://github.com/brafdlog/budget-tracking/discussions).

And [here](https://github.com/brafdlog/budget-tracking/issues?q=is%3Aopen+is%3Aissue+label%3AUI) are the UI related issues.

**Comment by Moshet** [comment]
I downloaded the software and I'll begin with the operational stuff:
1. What's the purpose of the upper horizontal menu?
2. I couldn't get any info scraped. 
2. A. On the first attempt, I was just waiting and nothing happened (therefore I think it's better to add some kind of active status bar that communicates what happens now instead of a spinning circle - actually two circles, which is also unnecessary). 
2. B. On the second attempt I got an error message that said "ENOTDIR, not a directory.". On this note - I think the error messages should be more informative.

UI remarks:
1. Colors should be match flat UI style. I'd go for a green theme (for example #2ecc71 - see more here: https://flatuicolors.com/)
2. Logo (new name first)
3. Buttons could use a more flat UI style - you can refer here for an example: https://uxdesign.cc/ui-cheat-sheets-buttons-7329ed9d6112

UX remarks are in the attached photo.

Let me know what you think
![IMG_20201228_133909](https://user-images.githubusercontent.com/70203664/103211977-4f15cd80-4912-11eb-8e82-72dcade5c79b.jpg)

**Comment by brafdlog** [comment]
Thanks!

Regarding the issues you have, I would like to understand the problem. There is an issue: #170 for the ENOTDIR. @baruchiro This should work in the latest version right? So @Moshet you can try downloading the latest version and see if there are still issues. If there are could you open an issue with how to reporuce?

Regarding the design and ux I just did a session with a designer that contributed some time to make a basic design for the near future. See [here](https://www.figma.com/file/iIDH1tpaCt0AZPmqQ9vECQ/Jonathan?node-id=50%3A461).

The logo and name are not up to date and there are two color palette options there.

I suggest that we base the discussion on that design because clearly the current ux is far from what we want.

WDYT?

**Comment by Moshet** [comment]
@brafdlog, I tried downloading again and the ENOTDIR error is still there. Maybe someone forgot to upload the newer version?

Regarding the UI - Looks great! I'd go for a greenish color which is more money related. 
Also good to see that we thought about a similar UX flow:) However, I'd go for a "less clicks"-design which is more similar to what I proposed. 
I.e. the user is entering the app, so it's clear that he wants to sync some financial data. So why should we make the user click on "add accounts" instead of just showing the user all the available financial institutions?
Also, there is no screen showing the scraped data.
I can talk to the designer too if you'd like me to.

**Comment by baruchiro** [comment]
Hi, @Moshet I'm working on it, we need to wait for #178 to finish. And please note I updated the link to the artifacts (https://github.com/brafdlog/budget-tracking/actions?query=workflow%3ABuild%2FRelease+branch%3Amaster)

**Comment by baruchiro** [comment]
Hi, we have a complete Figma design to implement. If you want to help and get access to Figma, please contact.

**Comment by brafdlog** [comment]
Implemented in new UI
