### ISSUE TITLE
Bump puppeteer-core from 5.5.0

### ISSUE THREAD

**Issue by baruchiro** [brafdlog/caspion#286]
We can't upgrade `puppeteer-core` because its types are broken: https://github.com/puppeteer/puppeteer/issues/7100

I think we should try to find a solution, since the puppeteer is a core library in our project. Please see the attached issue in puppeteer to see potential solutions.

**Comment by shacharRonZohar** [comment]
Is this still a relevant issue? It seems like puppeteer has reached version 20.1.2, which seems like a rather large jump from the current 5.5.0.

If this bump is still wanted I can try tackling it.

**Comment by baruchiro** [comment]
Yes, it is still relevant. Upgrading packages is sometimes hard in our project, but we have to do that!

There are some issues that I think we shouldn't try to solve before upgrading their packages.

Thank you!

**Comment by shacharRonZohar** [comment]
Hey, just wanted to give an update, due to some personal circumstances I have been unable to start work on this.
I'm posting this here because as much as I would love to come back to it when I can, in the meantime I don't want to block it, so if anyone wants to work on this, feel free!

I'll give another update here if \ when I am able to continue work on this.
