### ISSUE TITLE
Can't get inforamtion from Max credit card

### ISSUE THREAD

**Issue by UrielOfir** [brafdlog/caspion#305]
Error message:
Unknown transaction type כרטיס חליפי

**Comment by baruchiro** [comment]
Most of the time, errors during the scraping process are related to the core library, https://github.com/eshaham/israeli-bank-scrapers/, since we just give the credentials to it and it returning the transactions for us.

You need to check if this error occurs on our side or their. How you can do that? By debugging...

To debug our app, you need to add the `debugger` where you want to debug, and lunch the app, making sure the DevTools is open. The code will break on that command, in the DevTools.
Another option is, of course, to print log messages everywhere :-) and see them on the DevTools console.

It could be hard to start to debug, but I think this is one of the good ways to be familiar with a project, so be prepared and good luck!

**Comment by brafdlog** [comment]
I am using max successfully. Please reopen if still have an issue
