### ISSUE TITLE
Hash contains undefined string causing duplicate transactions

### ISSUE THREAD

**Issue by ReaBar** [brafdlog/caspion#473]
Since the latest release (1.11.7 - Cal fix) the hash column in the Google sheet contains concatenated 'undefined' string that causes duplicate transactions
example: `2023-04-19T14:45:00.000Z_-27.18_קוק סטוק_undefined_visaCal_2786`

**Comment by baruchiro** [comment]
I'm waiting for this https://github.com/eshaham/israeli-bank-scrapers/issues/781 to be solved, I think it will solve this problem.

**Comment by daniel-hauser** [comment]
@baruchiro

Since `memo` is [optional](https://github.com/eshaham/israeli-bank-scrapers/blob/580cc03173268ca86620df26cbb8a05401c88f52/src/transactions.ts#L49), sending undefined is allowed.

In moneyman is solved it (and future scrapers that will send `memo: undefined`) by replacing all nullish parts of the hash with an empty string.
See https://github.com/daniel-hauser/moneyman/pull/134/files

**Comment by baruchiro** [comment]
OK, the `undefined` problem is solved, but I afraid the hash will be still different because the `date` is now contains time.

I see no solution but to delete all the rows in Google Sheets for Visa Cal in the last X days, then run Caspion again.
